-- =========================================================
-- Pioneer Technical Resource Management System - Supabase Schema
-- Run this complete script in Supabase SQL Editor (supabase.com)
-- =========================================================

-- 1. Create 'projects' Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_card TEXT,
  contract TEXT,
  service_order TEXT,
  project TEXT,
  "desc" TEXT,
  unit TEXT,
  qty INTEGER DEFAULT 0,
  location TEXT,
  mob_date TEXT,
  exp_start TEXT,
  exp_end TEXT,
  act_start TEXT,
  act_end TEXT,
  assigned_to TEXT,
  team TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'employees' Table
CREATE TABLE IF NOT EXISTS public.employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id TEXT,
  name_en TEXT,
  name_ar TEXT,
  project TEXT,
  team TEXT,
  job_cat TEXT,
  vehicle_type TEXT,
  plate TEXT,
  brand TEXT,
  sec_expiry TEXT,
  vehicle_status TEXT,
  gate_pass TEXT,
  tools_box TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS) and allow Public Read/Write
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert on projects" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on projects" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on projects" ON public.projects FOR DELETE USING (true);

CREATE POLICY "Allow public read on employees" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Allow public insert on employees" ON public.employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on employees" ON public.employees FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on employees" ON public.employees FOR DELETE USING (true);

-- 4. Enable Realtime Publications
ALTER PUBLICATION supabase_realtime ADD TABLE public.projects;
ALTER PUBLICATION supabase_realtime ADD TABLE public.employees;

-- 5. Insert Initial Projects Data
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (1, 'JC-2026-007', '4400020478', '8501520961', 'Demi', 'Rehabilitation Of Demi Skids STG#1', '1', 1, 'SPP', '', '', '', '', '', 'Mustafa Elzemity', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (2, 'JC-2026-009', '4400022700', '8501572754', 'EXJ', 'Replacement Of Expansion Joints', '3', 10, 'SSPP', '2026-09-14', '2026-09-19', '2026-10-20', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (3, 'JC-2026-013', '4400022700', '', 'EXJ', 'Replacement Of HFO EXJ', '', 36, 'SSPP', '', '', '', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (4, 'JC-2026-010', '', '', 'EXJ', 'Replacement Of Expansion Joints', '', 22, 'SPP', '', '', '', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (5, 'JC-2026-014', '', '', 'EXJ', 'Replacement Of HFO EXJ', '', 1, 'SPP', '', '', '', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (6, 'JC-2026-011', '4400022700', '8501601097', 'EXJ', 'Replacement Of Expansion Joints', '', 4, 'JSPP', '', '', '', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (7, 'JC-2026-012', '', '', 'EXJ', 'Replacement Of Expansion Joints', '', 5, 'PP10', '', '', '', '', '', 'Yasser K. Alyamani', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (8, 'JC-2026-015', '', '', 'EDG', 'Maintenance Of Diesel Generators', '', 11, 'SPP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (9, 'JC-2026-002', '4400022688', '', 'EDG', 'Maintenance Of EDG#2', '', 1, 'SSPP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (10, 'JC-2026-003', '4400020917', '8501709736', 'EDG', 'Maintenenace Of Black Start Diesel Engines', '', 1, 'DPP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (11, 'JC-2026-004', '4400020917', '8501709743', 'EDG', 'Maintenenace Of Black Start Diesel Engines', '', 1, 'DPP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (12, 'JC-2026-005', '4400020917', '8501709744', 'EDG', 'Maintenenace Of Black Start Diesel Engines', '', 1, 'DPP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (13, 'JC-2026-006', '4400020917', '', 'EDG', 'Inspection & Minor PM', '', 1, 'Al-Wajh PP', '', '', '', '', '', 'Hassan Wahab', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (14, 'JC-2026-008', '4400022480', '8501510122', 'Oil Spill', 'Supply, installation, testing and commissioning oil spillage depilation equipment at jetty area for Response to deplete marine oil spills', '', 1, 'SSPP', '', '2025-07-26', '', '', '', 'Yasin Nagoor', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (15, 'JC-2026-016', '4400020478', '8501629275', 'Demi', 'Rehabilitation Of Demi Skids STG #2', '2', 1, 'SPP', '', '', '', '', '', 'Mustafa Elzemity', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (16, 'JC-2026-017', '4400020478', '8501629281', 'Demi', 'Rehabilitation Of Demi Skids STG #3', '3', 1, 'SPP', '', '', '', '', '', 'Mustafa Elzemity', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (17, 'JC-2026-018', '4400020478', '', 'Demi', 'Rehabilitation Of Demi Skids STG #4', '4', 1, 'SPP', '', '', '', '', '', 'Mustafa Elzemity', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;
INSERT INTO public.projects (id, job_card, contract, service_order, project, "desc", unit, qty, location, mob_date, exp_start, exp_end, act_start, act_end, assigned_to, team, remarks)
VALUES (18, 'JC-New', '', '', 'COA', 'COA', '', 0, 'Riyadh', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET
  job_card = EXCLUDED.job_card,
  contract = EXCLUDED.contract,
  service_order = EXCLUDED.service_order,
  project = EXCLUDED.project,
  "desc" = EXCLUDED."desc",
  unit = EXCLUDED.unit,
  qty = EXCLUDED.qty,
  location = EXCLUDED.location,
  mob_date = EXCLUDED.mob_date,
  exp_start = EXCLUDED.exp_start,
  exp_end = EXCLUDED.exp_end,
  act_start = EXCLUDED.act_start,
  act_end = EXCLUDED.act_end,
  assigned_to = EXCLUDED.assigned_to,
  team = EXCLUDED.team,
  remarks = EXCLUDED.remarks;

-- Reset projects id sequence
SELECT setval('public.projects_id_seq', (SELECT MAX(id) FROM public.projects));

-- 6. Insert Initial Employees (85 Workforce Records)
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (1, '20010', 'MOHAMED HASSANE MOHAMED ELGHOUL', 'محمد حسان محمد الغول', 'All', '-', 'Project Manager', 'Sedan', 'س أ ك 3584', '-', '2027-05-16', 'N/A', 'Yes', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (2, '20031', 'YASSER KHLAED A ALYAMANI', 'ياسر خالد عبده اليماني', 'Expansion Joint', 'B', 'Foreman', '-', '-', '-', '2027-08-01', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (3, '20035', 'MOHAMMED NOWFAL SHARAFUDEEN', 'محمد نوفل شرف الدين', 'DEMI', 'I', 'Engineer', 'Double Cab', 'ب ع ا 3158', 'Mitsubishi', '2027-04-27', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (4, '-', 'AHMAD', 'احمد', 'EDG', 'F', 'Engineer', '-', '-', '-', '2026-11-10', 'N/A', 'N/A', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (5, '20041', 'AHMAD SAMI M SENDI', 'أحمد سامي سندي', 'DEMI', 'K', 'Engineer', '-', '-', '-', '2026-10-14', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (6, '20042', 'GLENN GARCIA TANECA', 'جلين غارسيا تنيكا', 'COA', 'H', 'Skilled Technician', '-', '-', '-', '2027-01-17', 'N/A', 'N/A', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (7, '20043', 'QAIS RAZA MUREED HUSSAIN KHAWAJA', 'قيس رضا مريد حسين خواجه', 'COA', 'H', 'Technician', '-', '-', '-', '2027-02-11', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (8, '20044', 'MUHAMMAD HAMID FAZLI QADEEM', 'محمد حامد فضلي قديم', 'DEMI', 'I', 'Technician Ass.', '-', '-', '-', '2026-11-22', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (9, '20046', 'EDWIN SABALO PALMAN', 'ايدوين بالمن سابلو', 'EDG', 'F', 'Skilled Technician', 'Double Cab', 'ب ع ا 3159', 'Mitsubishi', '2027-02-12', 'Maintained', 'No', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (10, '20047', 'ABDULLAH RAZEEM KHAN', 'عبد الله رزيم خان', 'Expansion Joint', 'A', 'Team Leader', 'Double Cab', 'ب ص ط 4109', 'Mitsubishi', '2027-01-16', 'Maintained', 'No', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (11, '20048', 'ZAHID GUL RAHAT GUL', 'زاهد قل راحت قل', 'Expansion Joint', 'D', 'Team Leader', '-', '-', '-', '2026-12-01', 'N/A', 'N/A', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (12, '20051', 'MD SOHEL MD SOLAMAN', 'محمد سويل محمد سولامان', 'DEMI', 'I', 'Fabricator', 'Double Cab', 'ب ص ط 4109', 'Mitsubishi', '2026-12-11', 'Maintained', 'Yes', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (13, 'Need', 'Needs', 'Need', 'Expansion Joint', 'C', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (14, '20052', 'ANISH ANSARI NASARUDDIN ANSARI', 'انيش أنصاري نصرالدين أنصاري', 'Expansion Joint', 'C', 'Labor', '-', '-', '-', '2027-01-13', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (15, '20055', 'EDMAR ESCALA VILLAR', 'ادمار اسكالا بيلار', 'COA', 'H', 'Technician', 'Double Cab', 'ب ر ل 8219', 'Mitsubishi', '2027-05-13', 'Not Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (16, '20056', 'CHRISTOPHER ALUBA DUBLIN', 'كريستوفر الوبا دوبلين', 'EDG', 'G', 'Technician', 'Single Cab', 'ب ع ا 3153', 'Mitsubishi', '2027-01-09', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (17, '20149', 'SALEM HASSAN A OTHMAN', 'سالم حسن علي عثمان', 'Expansion Joint', 'C', 'Foreman', '-', '-', '-', '2027-09-22', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (18, '20057', 'HAMADA MAHROUS ALI ALI', 'حماده محروس علي علي', 'Expansion Joint', 'C', 'Team Leader', '-', '-', '-', '2026-12-20', 'N/A', 'N/A', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (19, 'Need', 'Needs', 'Need', 'Expansion Joint', 'B', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (20, '20058', 'AHMED MANSOUR MANSOUR RAMADAN', 'أحمد منصور منصور رمضان', 'Expansion Joint', 'B', 'Team Leader', '-', '-', '-', '2027-01-01', 'N/A', 'N/A', 'Required')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (21, '20059', 'NAZMUL HOQUE', 'نظم ال حقي', 'DEMI', 'K', 'Labor', '-', '-', '-', '2026-09-15', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (22, '20061', 'AZAHAR MIAH AZAHAR MIAH', 'أزهر ميدا ميدا ازهر', 'EDG', 'M', 'Labor', '-', '-', '-', '2027-01-18', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (23, '20148', 'ESSAM FATHI ABDELMONEIM METWALLI', 'عصام فتحى عبدالمنعم متولى', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '2026-11-25', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (24, '20063', 'SALMAN KHAN JAMALDAR', 'سلمان خان دار جمال', 'Expansion Joint', 'E', 'Team Leader', '-', '-', '-', '2026-11-04', 'N/A', 'No', 'Required')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (25, '20064', 'JAWAD KHAISTA RAHMAN', 'جواد خيسة رحمان رحمان', 'Expansion Joint', 'C', 'Labor', '-', '-', '-', '2027-02-02', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (26, '20065', 'FAZAL AMIN GUL AZEEM KHAN', 'فضل امين عظيم خان قل', 'EDG', 'F', 'Labor', '-', '-', '-', '2026-08-17', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (27, '20066', 'SAHA ALAM', 'ساها غلام', 'DEMI', 'K', 'Welder', 'Double Cab', 'ب ط ط 3646', 'Mitsubishi', '2026-12-26', 'Maintained', 'No', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (28, '20067', 'SAMI ALLAH GHAFOOR', 'سمي الله غفور', 'EDG', 'F', 'Labor', '-', '-', '-', '2026-11-05', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (29, '20068', 'FARHAN KHAN HASSAN KHAN', 'فرحان خان حسين  خان', 'Expansion Joint', 'C', 'Labor', '-', '-', '-', '2027-01-09', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (30, '20069', 'LUQMAN KHAN RAZEEM KHAN', 'لقمان خان رزيم خان', 'Expansion Joint', 'D', 'Labor', '-', '-', '-', '2026-12-06', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (31, '20070', 'ASIF SHAH MUAWAR SHAH', 'اصف شاه منور شاه', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '2026-12-09', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (32, '20071', 'GUL MUHAMMAD GUL SHARIF', 'جول محمد جول شريف', 'Expansion Joint', 'B', 'Labor', '-', '-', '-', '2027-01-08', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (33, '20075', 'MOHAMMAD MOKHTAR AMIN MOHAMMAD SARDAR', 'محمد مختار امين محمد سردار', 'Expansion Joint', 'B', 'Labor', 'Bus', 'ب ق ط 1825', 'GMC', '2027-01-09', 'Maintained', 'Yes', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (34, '20091', 'ABDUL SALAM', 'عبد ال سلام', 'DEMI', 'I', 'Welder', '-', '-', '-', '2027-04-23', 'N/A', 'N/A', 'Required')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (35, '20094', 'ELMIE PALOMAR GANOSA', 'المي بلومر قانوسا', 'EDG', 'G', 'Technician', '-', '-', '-', '2027-02-03', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (36, '20097', 'ERIC RUBIO LULAB', 'إريك روبيو لولاب', 'EDG', 'M', 'Technician', 'Double Cab', 'ب ص ط 4110', 'Mitsubishi', '2027-02-11', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (37, '20109', 'EUSEBIO JARDIN SABEROLA', 'إيوسيبيو سابرولا', 'COA', 'H', 'Labor', '-', '-', '-', '2027-01-28', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (38, '20116', 'CHARLESRYAN MACAPAGA MERCADO', 'تشارليز ريان ماكافاغال مير كادو', 'COA', 'H', 'Technician Ass.', '-', '-', '-', '2027-02-10', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (39, '20118', 'ARSHAD WALI SAID WALI', 'ارشد ولي سعيد ولي', 'Expansion Joint', 'C', 'Labor', '-', '-', '-', '2026-09-21', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (40, '20119', 'ADNAN KHAN ABDUL WALI KHAN', 'عدنان خان خان عبدالولي', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '2026-09-21', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (41, '20122', 'MUHAMMAD ZEESHAN MUHAMMAD YASIN', 'محمد زيشان محمد ياسين', 'COA', 'H', 'Technician', 'Double Cab', 'ب ص ط 4108', 'Mitsubishi', '2027-02-10', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (42, 'Need', 'Needs', 'Need', 'Expansion Joint', 'B', 'Fabricator', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (43, 'Need', 'Needs', 'Need', 'DEMI', 'K', 'Welder', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (44, '20125', 'ROBIUL HOSSAIN', 'ربيع ال ا ل أوسين', 'Expansion Joint', 'B', 'Labor', '-', '-', '-', '2027-03-19', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (45, '20127', 'YASIN NAGOOR SINTHAMATHAR', 'ياسين ناجور سنثامثر', 'Expansion Joint', 'A', 'Engineer', 'Double Cab', 'ب ص ط 4109', 'Mitsubishi', '2026-11-30', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (46, 'Need', 'Needs', 'Need', 'Expansion Joint', 'D', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (47, 'Need', 'Needs', 'Need', 'Expansion Joint', 'D', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (48, '20134', 'MD MAHADI HASAN', 'محمد مهدي حسن حسن', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '2027-04-14', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (49, '20136', 'KENT MANGHANO GOGO', 'كينت مانغانو مانغانو غوغو', 'COA', 'H', 'Technician Ass.', '-', '-', '-', '2026-09-28', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (50, 'Need', 'Needs', 'Need', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (51, 'Need', 'Needs', 'Need', 'Expansion Joint', 'A', 'Fabricator', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (52, '20155', 'MD SULAIMAN SHAH', 'محمد سليمان شاه شاه', 'Expansion Joint', 'A', 'Welder', '-', '-', '-', '2026-09-12', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (53, '20138', 'ADNAN KHAN ZAHID GUL', 'عدنان خان زاهد غول', 'Expansion Joint', 'D', 'Labor', '-', '-', '-', '2026-12-08', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (54, '20140', 'AZAD ABDUL HAKIM', 'أزاد عبد ال حكيم', 'Expansion Joint', 'B', 'Welder', '-', '-', '-', '2027-02-19', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (55, 'Need', 'Needs', 'Need', 'Expansion Joint', 'E', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (56, 'Need', 'Needs', 'Need', 'Expansion Joint', 'E', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (57, 'Need', 'Needs', 'Need', 'Expansion Joint', 'E', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (58, 'Need', 'Needs', 'Need', 'Expansion Joint', 'E', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (59, '20137', 'MUSTAFA ESSAM ALI ELZEMITY', 'مصطفى عصام على الزميتى', 'DEMI', 'I', 'Engineer', 'Double Cab', 'ب ع ا 3154', 'Mitsubishi', '2026-09-08', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (60, 'Need', 'Needs', 'Need', 'Expansion Joint', 'E', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (61, '20135', 'RYAN MORRE GOGO', 'ريان موري موري غوغو', 'EDG', 'F', 'Skilled Technician', 'Double Cab', 'ب س ن 9356', 'Mitsubishi', '2026-09-28', 'Maintained', 'No', 'Available')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (62, '20153', 'JAMAL SHEIKH RAHMAN', 'جمال شيخ الرحمن', 'DEMI', 'I', 'Welder', '-', '-', '-', '2027-01-06', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (63, 'Need', 'Needs', 'Need', 'DEMI', 'K', 'Fabricator', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (64, 'Need', 'Needs', 'Need', 'DEMI', 'I', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (65, 'Need', 'Needs', 'Need', 'DEMI', 'K', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (66, '20152', 'Zeshan Ali Muhammad Yaqub Tarar', 'زيشان علي محمد يعقوب تارار', 'EDG', 'M', 'Technician', '-', '-', '-', '2026-09-24', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (67, 'Need', 'Needs', 'Need', 'EDG', 'F', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (68, 'Need', 'Needs', 'Need', 'EDG', 'G', 'Foreman', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (69, 'Need', 'Needs', 'Need', 'EDG', 'M', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (70, 'Need', 'Needs', 'Need', 'EDG', 'M', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (71, 'Need', 'Needs', 'Need', 'EDG', 'M', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (72, 'Need', 'Needs', 'Need', 'EDG', 'F', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (73, 'Need', 'Needs', 'Need', 'EDG', 'F', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (74, 'Need', 'Needs', 'Need', 'EDG', 'G', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (75, 'Need', 'Needs', 'Need', 'EDG', 'G', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (76, 'Need', 'Needs', 'Need', 'EDG', 'G', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (77, '20156', 'HASSAN ABDULWAHAB M HAWSAWI', 'حسان عبدالوهاب محمد هوساوى', 'EDG', 'G', 'Engineer', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (78, '20128', 'ABDULRAHMAN GHURMULLAH ALGHAMDI', 'عبدالرحمن غرم الله الغامدي', 'EDG', 'M', 'Foreman', 'Double Cab', 'ب ق م 3502', 'Mitsubishi', '2027-04-19', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (79, '20021', 'MUTEB ABDULLAH ATEEQ ALLAH ALYOUBI', 'متعب عبدالله عتيق الله اليوبي', 'All', '-', 'Facility', '-', '-', '-', '2027-04-04', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (80, '20027', 'WALEED ALI ALHARBI', 'وليد علي حمود المزيني الحربي', 'All', '-', 'Facility', 'Single Cab', 'ب ط ح 8790', 'Mitsubishi', '2027-04-13', 'Maintained', 'No', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (81, '20036', 'NAWAF MASOUD ALMUZAINI', 'نواف المزيني مسعود المزيني', 'All', '-', 'Facility', '-', '-', '-', '2027-04-13', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (82, '20105', 'MOHAMMED JINID MOHAMMED ADODO', 'محمد جنيد محمد عدودو', 'All', '-', 'Facility', '-', '-', '-', '2027-04-21', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (83, 'Need', 'Needs', 'Need', 'Expansion Joint', 'A', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (84, 'Need', 'Needs', 'Need', 'DEMI', 'K', 'PTW', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;
INSERT INTO public.employees (id, emp_id, name_en, name_ar, project, team, job_cat, vehicle_type, plate, brand, sec_expiry, vehicle_status, gate_pass, tools_box)
VALUES (85, 'Need', 'Needs', 'Need', 'Expansion Joint', 'A', 'Labor', '-', '-', '-', '-', 'N/A', 'N/A', '-')
ON CONFLICT (id) DO UPDATE SET
  emp_id = EXCLUDED.emp_id,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  project = EXCLUDED.project,
  team = EXCLUDED.team,
  job_cat = EXCLUDED.job_cat,
  vehicle_type = EXCLUDED.vehicle_type,
  plate = EXCLUDED.plate,
  brand = EXCLUDED.brand,
  sec_expiry = EXCLUDED.sec_expiry,
  vehicle_status = EXCLUDED.vehicle_status,
  gate_pass = EXCLUDED.gate_pass,
  tools_box = EXCLUDED.tools_box;

-- Reset employees id sequence
SELECT setval('public.employees_id_seq', (SELECT MAX(id) FROM public.employees));
