export const INITIAL_DATA = {
  "projects": [
    {
      "id": 1,
      "jobCard": "JC-2026-007",
      "contract": "4400020478",
      "serviceOrder": "8501520961",
      "project": "Demi",
      "desc": "Rehabilitation Of Demi Skids STG#1",
      "unit": "1",
      "qty": 1,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Mustafa Elzemity",
      "team": "",
      "remarks": ""
    },
    {
      "id": 2,
      "jobCard": "JC-2026-009",
      "contract": "4400022700",
      "serviceOrder": "8501572754",
      "project": "EXJ",
      "desc": "Replacement Of Expansion Joints",
      "unit": "3",
      "qty": 10,
      "location": "SSPP",
      "mobDate": "2026-09-14",
      "expStart": "2026-09-19",
      "expEnd": "2026-10-20",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 3,
      "jobCard": "JC-2026-013",
      "contract": "4400022700",
      "serviceOrder": "",
      "project": "EXJ",
      "desc": "Replacement Of HFO EXJ",
      "unit": "",
      "qty": 36,
      "location": "SSPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 4,
      "jobCard": "JC-2026-010",
      "contract": "",
      "serviceOrder": "",
      "project": "EXJ",
      "desc": "Replacement Of Expansion Joints",
      "unit": "",
      "qty": 22,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 5,
      "jobCard": "JC-2026-014",
      "contract": "",
      "serviceOrder": "",
      "project": "EXJ",
      "desc": "Replacement Of HFO EXJ",
      "unit": "",
      "qty": 1,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 6,
      "jobCard": "JC-2026-011",
      "contract": "4400022700",
      "serviceOrder": "8501601097",
      "project": "EXJ",
      "desc": "Replacement Of Expansion Joints",
      "unit": "",
      "qty": 4,
      "location": "JSPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 7,
      "jobCard": "JC-2026-012",
      "contract": "",
      "serviceOrder": "",
      "project": "EXJ",
      "desc": "Replacement Of Expansion Joints",
      "unit": "",
      "qty": 5,
      "location": "PP10",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasser K. Alyamani",
      "team": "",
      "remarks": ""
    },
    {
      "id": 8,
      "jobCard": "JC-2026-015",
      "contract": "",
      "serviceOrder": "",
      "project": "EDG",
      "desc": "Maintenance Of Diesel Generators",
      "unit": "",
      "qty": 11,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 9,
      "jobCard": "JC-2026-002",
      "contract": "4400022688",
      "serviceOrder": "",
      "project": "EDG",
      "desc": "Maintenance Of EDG#2",
      "unit": "",
      "qty": 1,
      "location": "SSPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 10,
      "jobCard": "JC-2026-003",
      "contract": "4400020917",
      "serviceOrder": "8501709736",
      "project": "EDG",
      "desc": "Maintenenace Of Black Start Diesel Engines",
      "unit": "",
      "qty": 1,
      "location": "DPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 11,
      "jobCard": "JC-2026-004",
      "contract": "4400020917",
      "serviceOrder": "8501709743",
      "project": "EDG",
      "desc": "Maintenenace Of Black Start Diesel Engines",
      "unit": "",
      "qty": 1,
      "location": "DPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 12,
      "jobCard": "JC-2026-005",
      "contract": "4400020917",
      "serviceOrder": "8501709744",
      "project": "EDG",
      "desc": "Maintenenace Of Black Start Diesel Engines",
      "unit": "",
      "qty": 1,
      "location": "DPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 13,
      "jobCard": "JC-2026-006",
      "contract": "4400020917",
      "serviceOrder": "",
      "project": "EDG",
      "desc": "Inspection & Minor PM",
      "unit": "",
      "qty": 1,
      "location": "Al-Wajh PP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Hassan Wahab",
      "team": "",
      "remarks": ""
    },
    {
      "id": 14,
      "jobCard": "JC-2026-008",
      "contract": "4400022480",
      "serviceOrder": "8501510122",
      "project": "Oil Spill",
      "desc": "Supply, installation, testing and commissioning oil spillage depilation equipment at jetty area for Response to deplete marine oil spills",
      "unit": "",
      "qty": 1,
      "location": "SSPP",
      "mobDate": "",
      "expStart": "2025-07-26",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Yasin Nagoor",
      "team": "",
      "remarks": ""
    },
    {
      "id": 15,
      "jobCard": "JC-2026-016",
      "contract": "4400020478",
      "serviceOrder": "8501629275",
      "project": "Demi",
      "desc": "Rehabilitation Of Demi Skids STG #2",
      "unit": "2",
      "qty": 1,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Mustafa Elzemity",
      "team": "",
      "remarks": ""
    },
    {
      "id": 16,
      "jobCard": "JC-2026-017",
      "contract": "4400020478",
      "serviceOrder": "8501629281",
      "project": "Demi",
      "desc": "Rehabilitation Of Demi Skids STG #3",
      "unit": "3",
      "qty": 1,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Mustafa Elzemity",
      "team": "",
      "remarks": ""
    },
    {
      "id": 17,
      "jobCard": "JC-2026-018",
      "contract": "4400020478",
      "serviceOrder": "",
      "project": "Demi",
      "desc": "Rehabilitation Of Demi Skids STG #4",
      "unit": "4",
      "qty": 1,
      "location": "SPP",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "Mustafa Elzemity",
      "team": "",
      "remarks": ""
    },
    {
      "id": 18,
      "jobCard": "JC-New",
      "contract": "",
      "serviceOrder": "",
      "project": "COA",
      "desc": "COA",
      "unit": "",
      "qty": 0,
      "location": "Riyadh",
      "mobDate": "",
      "expStart": "",
      "expEnd": "",
      "actStart": "",
      "actEnd": "",
      "assignedTo": "",
      "team": "",
      "remarks": ""
    }
  ],
  "employees": [
    {
      "id": 1,
      "empId": "20010",
      "nameEn": "MOHAMED HASSANE MOHAMED ELGHOUL",
      "nameAr": "محمد حسان محمد الغول",
      "project": "All",
      "team": "-",
      "jobCat": "Project Manager",
      "vehicleType": "Sedan",
      "plate": "س أ ك 3584",
      "brand": "-",
      "secExpiry": "2027-05-16",
      "vehicleStatus": "N/A",
      "gatePass": "Yes",
      "toolsBox": "-"
    },
    {
      "id": 2,
      "empId": "20031",
      "nameEn": "YASSER KHLAED A ALYAMANI",
      "nameAr": "ياسر خالد عبده اليماني",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Foreman",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-08-01",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 3,
      "empId": "20035",
      "nameEn": "MOHAMMED NOWFAL SHARAFUDEEN",
      "nameAr": "محمد نوفل شرف الدين",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Engineer",
      "vehicleType": "Double Cab",
      "plate": "ب ع ا 3158",
      "brand": "Mitsubishi",
      "secExpiry": "2027-04-27",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 4,
      "empId": "-",
      "nameEn": "AHMAD",
      "nameAr": "احمد",
      "project": "EDG",
      "team": "F",
      "jobCat": "Engineer",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-11-10",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Available"
    },
    {
      "id": 5,
      "empId": "20041",
      "nameEn": "AHMAD SAMI M SENDI",
      "nameAr": "أحمد سامي سندي",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Engineer",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-10-14",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 6,
      "empId": "20042",
      "nameEn": "GLENN GARCIA TANECA",
      "nameAr": "جلين غارسيا تنيكا",
      "project": "COA",
      "team": "H",
      "jobCat": "Skilled Technician",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-17",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Available"
    },
    {
      "id": 7,
      "empId": "20043",
      "nameEn": "QAIS RAZA MUREED HUSSAIN KHAWAJA",
      "nameAr": "قيس رضا مريد حسين خواجه",
      "project": "COA",
      "team": "H",
      "jobCat": "Technician",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-02-11",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 8,
      "empId": "20044",
      "nameEn": "MUHAMMAD HAMID FAZLI QADEEM",
      "nameAr": "محمد حامد فضلي قديم",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Technician Ass.",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-11-22",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 9,
      "empId": "20046",
      "nameEn": "EDWIN SABALO PALMAN",
      "nameAr": "ايدوين بالمن سابلو",
      "project": "EDG",
      "team": "F",
      "jobCat": "Skilled Technician",
      "vehicleType": "Double Cab",
      "plate": "ب ع ا 3159",
      "brand": "Mitsubishi",
      "secExpiry": "2027-02-12",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "Available"
    },
    {
      "id": 10,
      "empId": "20047",
      "nameEn": "ABDULLAH RAZEEM KHAN",
      "nameAr": "عبد الله رزيم خان",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Team Leader",
      "vehicleType": "Double Cab",
      "plate": "ب ص ط 4109",
      "brand": "Mitsubishi",
      "secExpiry": "2027-01-16",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "Available"
    },
    {
      "id": 11,
      "empId": "20048",
      "nameEn": "ZAHID GUL RAHAT GUL",
      "nameAr": "زاهد قل راحت قل",
      "project": "Expansion Joint",
      "team": "D",
      "jobCat": "Team Leader",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-12-01",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Available"
    },
    {
      "id": 12,
      "empId": "20051",
      "nameEn": "MD SOHEL MD SOLAMAN",
      "nameAr": "محمد سويل محمد سولامان",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Fabricator",
      "vehicleType": "Double Cab",
      "plate": "ب ص ط 4109",
      "brand": "Mitsubishi",
      "secExpiry": "2026-12-11",
      "vehicleStatus": "Maintained",
      "gatePass": "Yes",
      "toolsBox": "-"
    },
    {
      "id": 13,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 14,
      "empId": "20052",
      "nameEn": "ANISH ANSARI NASARUDDIN ANSARI",
      "nameAr": "انيش أنصاري نصرالدين أنصاري",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-13",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 15,
      "empId": "20055",
      "nameEn": "EDMAR ESCALA VILLAR",
      "nameAr": "ادمار اسكالا بيلار",
      "project": "COA",
      "team": "H",
      "jobCat": "Technician",
      "vehicleType": "Double Cab",
      "plate": "ب ر ل 8219",
      "brand": "Mitsubishi",
      "secExpiry": "2027-05-13",
      "vehicleStatus": "Not Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 16,
      "empId": "20056",
      "nameEn": "CHRISTOPHER ALUBA DUBLIN",
      "nameAr": "كريستوفر الوبا دوبلين",
      "project": "EDG",
      "team": "G",
      "jobCat": "Technician",
      "vehicleType": "Single Cab",
      "plate": "ب ع ا 3153",
      "brand": "Mitsubishi",
      "secExpiry": "2027-01-09",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 17,
      "empId": "20149",
      "nameEn": "SALEM HASSAN A OTHMAN",
      "nameAr": "سالم حسن علي عثمان",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Foreman",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-09-22",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 18,
      "empId": "20057",
      "nameEn": "HAMADA MAHROUS ALI ALI",
      "nameAr": "حماده محروس علي علي",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Team Leader",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-12-20",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Available"
    },
    {
      "id": 19,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 20,
      "empId": "20058",
      "nameEn": "AHMED MANSOUR MANSOUR RAMADAN",
      "nameAr": "أحمد منصور منصور رمضان",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Team Leader",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-01",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Required"
    },
    {
      "id": 21,
      "empId": "20059",
      "nameEn": "NAZMUL HOQUE",
      "nameAr": "نظم ال حقي",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-15",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 22,
      "empId": "20061",
      "nameEn": "AZAHAR MIAH AZAHAR MIAH",
      "nameAr": "أزهر ميدا ميدا ازهر",
      "project": "EDG",
      "team": "M",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-18",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 23,
      "empId": "20148",
      "nameEn": "ESSAM FATHI ABDELMONEIM METWALLI",
      "nameAr": "عصام فتحى عبدالمنعم متولى",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-11-25",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 24,
      "empId": "20063",
      "nameEn": "SALMAN KHAN JAMALDAR",
      "nameAr": "سلمان خان دار جمال",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "Team Leader",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-11-04",
      "vehicleStatus": "N/A",
      "gatePass": "No",
      "toolsBox": "Required"
    },
    {
      "id": 25,
      "empId": "20064",
      "nameEn": "JAWAD KHAISTA RAHMAN",
      "nameAr": "جواد خيسة رحمان رحمان",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-02-02",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 26,
      "empId": "20065",
      "nameEn": "FAZAL AMIN GUL AZEEM KHAN",
      "nameAr": "فضل امين عظيم خان قل",
      "project": "EDG",
      "team": "F",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-08-17",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 27,
      "empId": "20066",
      "nameEn": "SAHA ALAM",
      "nameAr": "ساها غلام",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Welder",
      "vehicleType": "Double Cab",
      "plate": "ب ط ط 3646",
      "brand": "Mitsubishi",
      "secExpiry": "2026-12-26",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "Available"
    },
    {
      "id": 28,
      "empId": "20067",
      "nameEn": "SAMI ALLAH GHAFOOR",
      "nameAr": "سمي الله غفور",
      "project": "EDG",
      "team": "F",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-11-05",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 29,
      "empId": "20068",
      "nameEn": "FARHAN KHAN HASSAN KHAN",
      "nameAr": "فرحان خان حسين  خان",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-09",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 30,
      "empId": "20069",
      "nameEn": "LUQMAN KHAN RAZEEM KHAN",
      "nameAr": "لقمان خان رزيم خان",
      "project": "Expansion Joint",
      "team": "D",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-12-06",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 31,
      "empId": "20070",
      "nameEn": "ASIF SHAH MUAWAR SHAH",
      "nameAr": "اصف شاه منور شاه",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-12-09",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 32,
      "empId": "20071",
      "nameEn": "GUL MUHAMMAD GUL SHARIF",
      "nameAr": "جول محمد جول شريف",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-08",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 33,
      "empId": "20075",
      "nameEn": "MOHAMMAD MOKHTAR AMIN MOHAMMAD SARDAR",
      "nameAr": "محمد مختار امين محمد سردار",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Labor",
      "vehicleType": "Bus",
      "plate": "ب ق ط 1825",
      "brand": "GMC",
      "secExpiry": "2027-01-09",
      "vehicleStatus": "Maintained",
      "gatePass": "Yes",
      "toolsBox": "-"
    },
    {
      "id": 34,
      "empId": "20091",
      "nameEn": "ABDUL SALAM",
      "nameAr": "عبد ال سلام",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Welder",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-04-23",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "Required"
    },
    {
      "id": 35,
      "empId": "20094",
      "nameEn": "ELMIE PALOMAR GANOSA",
      "nameAr": "المي بلومر قانوسا",
      "project": "EDG",
      "team": "G",
      "jobCat": "Technician",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-02-03",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 36,
      "empId": "20097",
      "nameEn": "ERIC RUBIO LULAB",
      "nameAr": "إريك روبيو لولاب",
      "project": "EDG",
      "team": "M",
      "jobCat": "Technician",
      "vehicleType": "Double Cab",
      "plate": "ب ص ط 4110",
      "brand": "Mitsubishi",
      "secExpiry": "2027-02-11",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 37,
      "empId": "20109",
      "nameEn": "EUSEBIO JARDIN SABEROLA",
      "nameAr": "إيوسيبيو سابرولا",
      "project": "COA",
      "team": "H",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-28",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 38,
      "empId": "20116",
      "nameEn": "CHARLESRYAN MACAPAGA MERCADO",
      "nameAr": "تشارليز ريان ماكافاغال مير كادو",
      "project": "COA",
      "team": "H",
      "jobCat": "Technician Ass.",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-02-10",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 39,
      "empId": "20118",
      "nameEn": "ARSHAD WALI SAID WALI",
      "nameAr": "ارشد ولي سعيد ولي",
      "project": "Expansion Joint",
      "team": "C",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-21",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 40,
      "empId": "20119",
      "nameEn": "ADNAN KHAN ABDUL WALI KHAN",
      "nameAr": "عدنان خان خان عبدالولي",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-21",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 41,
      "empId": "20122",
      "nameEn": "MUHAMMAD ZEESHAN MUHAMMAD YASIN",
      "nameAr": "محمد زيشان محمد ياسين",
      "project": "COA",
      "team": "H",
      "jobCat": "Technician",
      "vehicleType": "Double Cab",
      "plate": "ب ص ط 4108",
      "brand": "Mitsubishi",
      "secExpiry": "2027-02-10",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 42,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Fabricator",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 43,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Welder",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 44,
      "empId": "20125",
      "nameEn": "ROBIUL HOSSAIN",
      "nameAr": "ربيع ال ا ل أوسين",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-03-19",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 45,
      "empId": "20127",
      "nameEn": "YASIN NAGOOR SINTHAMATHAR",
      "nameAr": "ياسين ناجور سنثامثر",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Engineer",
      "vehicleType": "Double Cab",
      "plate": "ب ص ط 4109",
      "brand": "Mitsubishi",
      "secExpiry": "2026-11-30",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 46,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "D",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 47,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "D",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 48,
      "empId": "20134",
      "nameEn": "MD MAHADI HASAN",
      "nameAr": "محمد مهدي حسن حسن",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-04-14",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 49,
      "empId": "20136",
      "nameEn": "KENT MANGHANO GOGO",
      "nameAr": "كينت مانغانو مانغانو غوغو",
      "project": "COA",
      "team": "H",
      "jobCat": "Technician Ass.",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-28",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 50,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 51,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Fabricator",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 52,
      "empId": "20155",
      "nameEn": "MD SULAIMAN SHAH",
      "nameAr": "محمد سليمان شاه شاه",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Welder",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-12",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 53,
      "empId": "20138",
      "nameEn": "ADNAN KHAN ZAHID GUL",
      "nameAr": "عدنان خان زاهد غول",
      "project": "Expansion Joint",
      "team": "D",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-12-08",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 54,
      "empId": "20140",
      "nameEn": "AZAD ABDUL HAKIM",
      "nameAr": "أزاد عبد ال حكيم",
      "project": "Expansion Joint",
      "team": "B",
      "jobCat": "Welder",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-02-19",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 55,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 56,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 57,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 58,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 59,
      "empId": "20137",
      "nameEn": "MUSTAFA ESSAM ALI ELZEMITY",
      "nameAr": "مصطفى عصام على الزميتى",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Engineer",
      "vehicleType": "Double Cab",
      "plate": "ب ع ا 3154",
      "brand": "Mitsubishi",
      "secExpiry": "2026-09-08",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 60,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "E",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 61,
      "empId": "20135",
      "nameEn": "RYAN MORRE GOGO",
      "nameAr": "ريان موري موري غوغو",
      "project": "EDG",
      "team": "F",
      "jobCat": "Skilled Technician",
      "vehicleType": "Double Cab",
      "plate": "ب س ن 9356",
      "brand": "Mitsubishi",
      "secExpiry": "2026-09-28",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "Available"
    },
    {
      "id": 62,
      "empId": "20153",
      "nameEn": "JAMAL SHEIKH RAHMAN",
      "nameAr": "جمال شيخ الرحمن",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Welder",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-01-06",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 63,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Fabricator",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 64,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "DEMI",
      "team": "I",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 65,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "DEMI",
      "team": "K",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 66,
      "empId": "20152",
      "nameEn": "Zeshan Ali Muhammad Yaqub Tarar",
      "nameAr": "زيشان علي محمد يعقوب تارار",
      "project": "EDG",
      "team": "M",
      "jobCat": "Technician",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2026-09-24",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 67,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "F",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 68,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "G",
      "jobCat": "Foreman",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 69,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "M",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 70,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "M",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 71,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "M",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 72,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "F",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 73,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "F",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 74,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "G",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 75,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "G",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 76,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "EDG",
      "team": "G",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 77,
      "empId": "20156",
      "nameEn": "HASSAN ABDULWAHAB M HAWSAWI",
      "nameAr": "حسان عبدالوهاب محمد هوساوى",
      "project": "EDG",
      "team": "G",
      "jobCat": "Engineer",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 78,
      "empId": "20128",
      "nameEn": "ABDULRAHMAN GHURMULLAH ALGHAMDI",
      "nameAr": "عبدالرحمن غرم الله الغامدي",
      "project": "EDG",
      "team": "M",
      "jobCat": "Foreman",
      "vehicleType": "Double Cab",
      "plate": "ب ق م 3502",
      "brand": "Mitsubishi",
      "secExpiry": "2027-04-19",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 79,
      "empId": "20021",
      "nameEn": "MUTEB ABDULLAH ATEEQ ALLAH ALYOUBI",
      "nameAr": "متعب عبدالله عتيق الله اليوبي",
      "project": "All",
      "team": "-",
      "jobCat": "Facility",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-04-04",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 80,
      "empId": "20027",
      "nameEn": "WALEED ALI ALHARBI",
      "nameAr": "وليد علي حمود المزيني الحربي",
      "project": "All",
      "team": "-",
      "jobCat": "Facility",
      "vehicleType": "Single Cab",
      "plate": "ب ط ح 8790",
      "brand": "Mitsubishi",
      "secExpiry": "2027-04-13",
      "vehicleStatus": "Maintained",
      "gatePass": "No",
      "toolsBox": "-"
    },
    {
      "id": 81,
      "empId": "20036",
      "nameEn": "NAWAF MASOUD ALMUZAINI",
      "nameAr": "نواف المزيني مسعود المزيني",
      "project": "All",
      "team": "-",
      "jobCat": "Facility",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-04-13",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 82,
      "empId": "20105",
      "nameEn": "MOHAMMED JINID MOHAMMED ADODO",
      "nameAr": "محمد جنيد محمد عدودو",
      "project": "All",
      "team": "-",
      "jobCat": "Facility",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "2027-04-21",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 83,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 84,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "DEMI",
      "team": "K",
      "jobCat": "PTW",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    },
    {
      "id": 85,
      "empId": "Need",
      "nameEn": "Needs",
      "nameAr": "Need",
      "project": "Expansion Joint",
      "team": "A",
      "jobCat": "Labor",
      "vehicleType": "-",
      "plate": "-",
      "brand": "-",
      "secExpiry": "-",
      "vehicleStatus": "N/A",
      "gatePass": "N/A",
      "toolsBox": "-"
    }
  ]
};
